mcq/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from mcqapp import views

urlpatterns = [
    url(r'^$', views.index, name ='index'),
    url(r'^mcqapp/', include('mcqapp.urls')),
    path('admin/', admin.site.urls),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'special/', views.special, name='special'),
    path('social-auth/', include('social_django.urls', namespace="social")),
]

mcqapp/urls.py
from django.conf.urls import url
from mcqapp import views

#Template URLs
app_name = 'mcqapp'

urlpatterns = [
    url(r'^register/$', views.register, name = 'register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
]

mcqapp/models.py
from django.db import models
#import basic user models
from django.contrib.auth.models import User


# Create your models here.
class User:
    total_score = models.IntegerField(default=0)


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #additional attributes
    portfolio_site = models.URLField(blank=True)

    #Pillow library should be installed for ImageField - pip install pillow
    profile_pic = models.ImageField(upload_to='mcqapp/profile_pics', blank=True)

    def __str__(self):
        return self.user.username

mcqapp/forms.py
from django import forms
from django.contrib.auth.models import User
from mcqapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

#connects model to actual userProfileInfo model
    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

mcqapp/views.py
from django.shortcuts import render
from mcqapp.forms import UserForm, UserProfileInfoForm

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout



# Create your views here.
def index(request):
    return render(request, 'mcqapp/index.html')

@login_required
def special(request):
    return HttpResponse("You are Logged in, nice")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if(user_form.is_valid() and profile_form.is_valid()):
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print('user_form.errors, profile_form.errors')

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'mcqapp/registration.html',
        {'user_form':user_form,
        'profile_form': profile_form,
        'registered': registered})

def user_login(request):
    if(request.method == 'POST'):
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account is not active")

        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password: {}".format(username, password))
            return HttpResponse("invalid login details supplied!")

    else:
        return render(request, 'mcqapp/login.html', {})

templates/mcqapp/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/index.css'%}">
  </head>
  <body>
    <div class="container">
    <nav class = 'navbar navbar-default navbar-static-top'>

          <a class = 'navbar-brand' href="{% url 'index' %}">WeTheKoders</a>
          <a class = 'navbar-link' href="{% url 'admin:index' %}">Admin</a>
          <a class = 'navbar-link' href="{% url 'mcqapp:register' %}">Register</a>
          {%if user.is_authenticated %}
            <a class = 'navbar-link' href="{%url 'logout' %}">Logout</a>
          {%else%}
            <a class = 'navbar-link' href="{%url 'mcqapp:user_login'%}">Login</a>
          {%endif%}
    </nav>
    </div>
    <div class="container-fluid">
      <div class="card p-5">
        {%block body_block%}
        {% endblock %}
      </div>

    </div>

  </body>
</html>

templates/mcqapp/index.html
{% extends "mcqapp/base.html" %}

{%block body_block%}

<div class="row">
        <div class="col-sm-12 mb-3">
          {%if user.username%}
            <h4 class="text-center">Welcome {{ user.username }}</h4>
          {%else%}
            <h4 class="text-center">Welcome to WeTheKoders. </h4>
            <h4 class="text-center">Login or Register to continue. </h4>
          {%endif%}
        </div>

            <!-- Add from here -->
        {% for ass in backends.associated %}
          {% if ass.provider == 'facebook' %}
            <div class="col-md-6 text-center">
                <img src="{{ass.extra_data.picture.data.url}}" alt="" width="150" height="150" style="border-radius: 50%">
            </div>
            <div class="col-md-6 social-container my-2">                 <p> Signed in via:  {{ ass.provider }} </p>
                <p> Name:  {{ ass.extra_data.name }} </p>
                <p> Provider url: <a href="{{ass.extra_data.profile_url}}">link</a></p>
            </div>
          {% endif %}
        {% endfor %}

            <!-- End here -->
      </div>

{%endblock%}

templates/mcqapp/login.html
{%extends 'mcqapp/base.html'%}
{%block body_block%}
<div class="jumbotron">
  <h3>Please login:</h3>
  <p></p>
  <form class="" action="{%url 'mcqapp:user_login'%}" method="post">
    {%csrf_token%}
    <label for="username">UserName:</label>
    <input type="text" name="username" placeholder="Enter username here">
    <p></p>
    <label for="password">Password:</label>
    <input type="password" name="password" >
    <p></p>
    <input type="submit" name="" value="Login">
    <p></p>
    <div class="row">
        <div class="mx-auto social-container my-2 order-md-1">
            <button class="btn btn-danger  mb-2">
                <a href="{%url 'social:begin' 'instagram'%}">Login with Instagram</a>
            </button>
            <p></p>
            <button class="btn btn-primary mb-2">
                <a href="{% url 'social:begin' 'facebook'%} ">Login with Facebook</a>
            </button>
            <p></p>
            <button class="btn btn-info mb-2">
                <a href="{% url 'social:begin' 'linkedin'%} ">Login with LinkedIn</a>
            </button>
        </div>
    </div>

  </form>
</div>

{%endblock%}

templates/mcqapp/registration.html
{%extends "mcqapp/base.html"%}

{% load static %}

{%block body_block%}
<div class="jumbotron">
  {%if registered%}
    <h1>Thank you for registering</h1>
  {%else%}
    <h2>Please, Register here:</h2>
    <p></p>
    <h3>Fill out the form: </h3>
    <p></p>

<!-- for image uploading, use enctype -->
    <form enctype="multipart/form-data" method="post">
      {%csrf_token%}
      {{user_form.as_p}}
      {{profile_form.as_p}}
      <input type="submit"  value="Register">
    </form>

  {%endif%}
</div>

{%endblock%}